config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'

  get "xbox", to: "games#xbox"
  get "ps4", to: "games#ps4"
  get "switch", to: "games#switch"


  get "dashboard", to: "games#dashboard"
  get "reservation_dashboard", to: "reservations#reservation_dashboard"
    
  resources :games do
    resources :reservations, only: [ :new, :create ]
  end
  resources :reservations, only: [ :index, :show, :reservation_dashboard, :edit, :update, :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reservations
  has_many :reviews
  validates :name, presence: true
  validates :price, presence: true
  validates :platform, presence: true

  def owner
    user
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  def owner
    game.user
  end

  def renter
    user
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates :content, presence: true
  validates :rating, presence: true
  def owner
    game.user
  end

  def renter
    user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :reservations
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

#   before_action :authenticate_user!

  def configure_permitted_parameters
#     # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

#     # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @game = Game.new

  end

  def dashboard
    @games = current_user.games
  end

  def xbox
    @games = Game.where("platform LIKE 'Xbox%'")
    # query = SELECT * FROM games WHERE platform = "Xbox"
    # @games = ActiveRecord::Base.connection.execute(query)
  end

  def ps4
    @games = Game.where("platform LIKE 'PS4%'")
  end

  def switch
    @games = Game.where("platform LIKE 'Nintendo%'")
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    if @game.save
      redirect_to dashboard_path(dashboard), notice: 'Game was successfully created'
    else
      render 'new'
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to dashboard_path(current_user), notice: 'Game was successfully destroyed'
  end

  private

  def game_params
    params.require(:game).permit(:name, :price, :platform, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservation = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @game = Game.find(params[:game_id])
    @reservation = Reservation.new
  end

  def reservation_dashboard
    @reservations = current_user.reservations
  end

  def create
    @reservation = Reservation.new(reservation_params)
    game = Game.find(params[:game_id])
    user = current_user
    @reservation.game = game
    @reservation.user = user
    @reservation.status = "pending"
    @reservation.save
    redirect_to reservation_dashboard_path(@reservation)
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_status_params)

    redirect_to reservation_path(@reservation)
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservation_dashboard_path, notice: 'The reservation was successfully removed'
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

  def reservation_status_params
    params.require(:reservation).permit(:status)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def show

end
  def create
    @review = Review.new(review_params)
    @game = Game.find(params[:game_id])
    @review.game = @game
    if @review.save
      redirect_to game_path(@game), notice: 'Nice review!!'
    else
      render 'games/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/dashboard.html.erb
<div class="dashboard-main-container">
  <div class="banner-individual-pages" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url(https://images.pexels.com/photos/1373100/pexels-photo-1373100.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500);">
    <div class="container">
      <div class="row justify-content-between">
      </div>
      <h1 class="text-center" style="color:white; padding-top: 8rem; font-size: 80px;">Games you own</h1>
      <div class="row justify-content-center">
        <h1 style="color: white;"></h1>
      </div>
    </div>
  </div>
  <div class="cards">
    <% @games.each do |game| %>
      <% if game.photo.attached?%>
        <% background_url = cl_image_path game.photo.key %>
      <% else %>
        <% background_url = 'https://images.unsplash.com/photo-1510015632688-f18aa4c1a95e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80' %>
      <% end %>
      <%= link_to game_path(game) do  %>
        <div class="card">
          <div class="additional" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.4)), 
            url(https://images.pexels.com/photos/326240/pexels-photo-326240.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260); 
            background-size: cover; background-position: center;">
            <div class="user-card">
              <div class="coords">
                <div class="stats" style="position: absolute">
                  <div class="text-box">
                    <p style="font-size: 12px; color: black; line-height: 4px; color: white;">Reservations</p>
                    <% game.reservations.each do |reservation| %>
                      <p style="font-size: 16px; padding: 5px; border-radius: 5px; <%= reservation.status == "Available" ? "background-color: #09ff18bd;" : "background-color: #ff0909b8;" %>"><%=  reservation.start_date.strftime("%m/%d")  %> - <%=  reservation.end_date.strftime("%m/%d")  %> </p>
                    <% end %>
                  </div>
                </div>
              </div>
            <div class="more-info" style="position: absolute">
              <h1 style="color: white;"><%= game.name %></h1>
              <div>
                <% if game.user.photo.attached?%>
                  <%= cl_image_tag game.user.photo.key, class: "avatar-large", style: "position: absolute"%>
                <% else %>
                  <%= cl_image_tag "https://images.unsplash.com/photo-1529699310859-b163e33e4556?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1122&q=80", class: "avatar-large" %>
                <% end %>
              </div>
              <div class="user-name text-center" style="color: white; font-size: bold; margin-top: 5.5rem;">
                <%= game.user.name %>
              </div>
            </div>
          </div>
        </div>
        <div class="general">
          <div class="card-category" style="background-image: url('<%= background_url %>')"></div>
          <span class="more">Mouse over the card for more info</span>
        </div>
        
        </div>
      <% end %>
    <% end %>
  </div>

app/views/games/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1><%= @game.name %></h1>

      <%= simple_form_for @game do |f| %>
        <%= f.input :name %>
        <%= f.input :price %>
        <%= f.input :genre %>
        <%= f.input :platform %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="index-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url(https://images.unsplash.com/photo-1486572788966-cfd3df1f5b42?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1952&q=80);">
    <div class="container">
      <div class="row justify-content-between">
      </div>
      <h1 class="text-center" style="color:white; padding-top: 24rem;">Choose from our most popular platforms</h1>
      <div class="row justify-content-center">
        <%= link_to xbox_path, class: "m-4", style:"color: white; border-radius: 8px;" do %>
          <%= image_tag "xbox.png", class: "icon-style", style:"height: 50px; width: 50px;" %>
        <% end %>
        <%= link_to ps4_path, class: "btn btn-light btn-lg m-4", style:"height: 60px; width: 90px; color: white; border-radius: 8px;" do %>
          <%= image_tag "game.png", class: "icon-style", style:"height: 50px; width: 50px;" %>
        <% end %>
        <%= link_to switch_path, class: "m-4", style:" color: white; border-radius: 8px;" do %>
          <%= image_tag "nintendo.png", class: "icon-style", style:"height: 50px; width: 50px;" %>
        <% end %>
      </div>
      <h4 class="text-center" style="color:white; padding-top: 1rem;">Or scroll down for more amazing titles</h4>
    </div>
  </div>
  <div class="cards">
    <% @games.each do |game| %>
      <% if game.photo.attached?%>
        <% background_url = cl_image_path game.photo.key %>
      <% else %>
        <% background_url = 'https://images.unsplash.com/photo-1510015632688-f18aa4c1a95e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80' %>
      <% end %>
      <%= link_to game_path(game) do  %>
        <%= render "/shared/card", game: game, background_url: background_url do |game|%>
          <div class="text-box">
            <i class="fas fa-tag" style="color: whitesmoke"></i>
            <div class="value">$<%= game.price %></div>
          </div>
          <div class="text-box">
            <i class="fa fa-gamepad" style="color: white"></i>
            <div class="value"><%= game.platform %></div>
          </div>
          <div class="text-box">
            <i class="fas fa-tv" style="color: white"></i>
            <div class="value"><%= game.genre %></div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new game</h1>

      <%= simple_form_for @game do |f| %>
        <%= f.input :name %>
        <%= f.input :price %>
        <%= f.input :platform, collection: [ 
            "PC",
            "Xbox",
            "PS4",
            "Nintendo DS",
            "Nintendo Switch",
            "Sega Saturn",
            "Gamecube",
            "Nintendo Wii"
          ] %>
        <%= f.input :genre, collection: [ 
            "Action", 
            "First Person Shooter",
            "Simulation",
            "Racing",
            "Sports",
            "RPG",
            "MMORPG",
            "Real Time Strategy",
            "Platform",
            "Fighting",
            "Rhythm",
            "Stealth",
            "Survival"
          ] %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/ps4.html.erb
<div class="banner-ps4" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url(https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1507457379470-08b800bebc67%3Fixlib%3Drb-1.2.1%26ixid%3DeyJhcHBfaWQiOjEyMDd9%26auto%3Dformat%26fit%3Dcrop%26w%3D1568%26q%3D80);">
    <div class="container">
      <div class="row justify-content-between">
      </div>
      <h1 class="text-center" style="color:white; padding-top: 8rem; font-size: 80px;">Playstation 4</h1>
      <div class="row justify-content-center">
        <h1 style="color: white;"></h1>
      </div>
    </div>
  </div>
  <div class="cards">
    <% @games.each do |game| %>
      <% if game.photo.attached?%>
        <% background_url = cl_image_path game.photo.key %>
      <% else %>
        <% background_url = 'https://images.unsplash.com/photo-1510015632688-f18aa4c1a95e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80' %>
      <% end %>
      <%= link_to game_path(game) do  %>
        <div class="card">
          <div class="additional" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), 
            url(https://images.pexels.com/photos/2520829/pexels-photo-2520829.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260); 
            background-size: cover; background-position: center;">
            <div class="user-card">
              <div class="coords">
                <div class="stats">
                  <div class="text-box">
                    <i class="fas fa-tag" style="color: white;"></i>
                    <div class="value">$<%= game.price %></div>
                  </div>
                  <div class="text-box">
                    <i class="fa fa-gamepad" style="color: white;"></i>
                    <div class="value"><%= game.platform %></div>
                  </div>
                  <div class="text-box">
                    <i class="fas fa-tv" style="color: white;"></i>
                    <div class="value"><%= game.genre %></div>
                  </div>
                </div>
              </div>
              
              
            </div>
            <div class="more-info">
              <h1 style="color: white;"><%= game.name %></h1>
              <div>
                <% if game.user.photo.attached?%>
                  <%= cl_image_tag game.user.photo.key, class: "avatar-large"%>
                <% else %>
                  <%= cl_image_tag "https://images.unsplash.com/photo-1529699310859-b163e33e4556?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1122&q=80", class: "avatar-large" %>
                <% end %>
              </div>
              <div class="user-name text-center" style="color: white">
                <%= game.user.name %>
              </div>
            </div>
          </div>
          <div class="general">
            <div class="card-category" style="background-image: url('<%= background_url %>')">
            </div>
            <span class="more">Mouse over the card for more info</span>
          </div>
        </div> 
      <% end %> 
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row game-info" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4)), 
            url(https://images.pexels.com/photos/326240/pexels-photo-326240.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260); 
            background-size: cover; background-position: center;">
    <div class="col-sm-12 col-md-6">
      <h1 class="text-center" style="color: white; font-size: bold;"><%= @game.name %></h1>
      <div class="game-photo">
          <% if @game.photo.attached?%>
            <%= cl_image_tag @game.photo.key, height: 500, width: 500, crop: :scale, :radius => 16 %>
          <% else %>
            <%= cl_image_tag("f0e6lzfzkmdqtzfblz6t", width: 400, height: 300, crop: :scale, :radius => 16) %>
          <% end %>
       </div>
  </div>
       <div class="row_reservation">
          <table class="table" style="line-height: 1rem; ">
            <tbody>
              <thead>
                <th><i class="fas fa-tag", style="font-size: 26px; color: white;"></i></th>
                <th><i class="fas fa-tv", style="font-size: 26px; color: white;"></i></th>
                <th><i class="fa fa-gamepad", style="font-size: 26px; color: white;"></i></th>
                <th>
                  <% if @game.user.photo.attached?%>
                    <%= cl_image_tag @game.user.photo.key, class: "avatar-show"%>
                  <% else %>
                    <%= cl_image_tag "https://images.unsplash.com/photo-1529699310859-b163e33e4556?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1122&q=80", class: "avatar-show" %>
                  <% end %>
                </th>
                <% if current_user.id == @game.user_id %>
                  <th style="color: white;">Delete</th>
                <% end %>
              </thead>
            <% @game.name%>
              <tr>
                <td style="color: white;">$<%= @game.price %></td>
                <td style="color: white;"><%= @game.genre %></td>
                <td style="color: white;"><%= @game.platform %></td>
                <td style="color: white;"><%= @game.user.name %></td>
                <td>
                  <% if current_user.id == @game.user_id %>
                    <%= link_to game_path(@game), method: :delete, data: { confirm: "Are you sure?" } do %>
                      <i class="fa fa-trash destroy_dose", style="color: red;"></i>
                    <% end %>
                  <% else %>
                    <p></p>
                  <% end %>
                </td>
              </tr>
              <div class="form-wrapper" style="width: 400px; margin: 0 auto; "></div>
          </tbody>
        </table>
          <div class="calender" style="padding-top: 30px;" >
            <% if current_user.id == @game.user_id %>
              <p style="color: white; font-size: 21px; padding-bottom: 1rem;">Reservation history for <%= @game.name %></p>
              <% @game.reservations.each do |reservation| %>
                <div style="height: 14rem; padding-top: 1rem;">
                  <p style="margin-bottom: 3rem; color: white; font-size: 16px; padding: 5px; border-radius: 5px; <%= reservation.status == "Available" ? "background-color: #09ff18bd;" : "background-color: #ff0909b8;" %>"><%=  reservation.start_date.strftime("%m/%d")  %> - <%=  reservation.end_date.strftime("%m/%d")  %> </p>
                  <div class="margin-top: 1rem;">
                  <%= link_to "Edit Status", edit_reservation_path(reservation), class: "your-game-btn", style:"color: white;" %>
                  </div>
                </div>
              <% end %>
            <% else %>
                <%= simple_form_for [@game, @reservation] do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"}, class:"color: white;" %>
                <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <%= f.button :submit, "Reserve", class: "btn btn-primary" %>
                <% end %>
            <% end %>
          </div>
     </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Game Exchange</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Edit reservation status</h1>

      <%= simple_form_for @reservation do |f| %>
        <%= f.input :status, collection: ['Pending', 'Available', 'Unavailable'], required: false %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Make a Reservation for <%= @game.name%></h2>

    <%= simple_form_for [@game, @reservation] do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reservations/reservation_dashboard.html.erb
<div class="dashboard-main-container">
  <div class="banner-individual-pages" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url(https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1955&q=80);">
    <div class="container">
      <div class="row justify-content-between">
      </div>
      <h1 class="text-center" style="color:white; padding-top: 8rem; font-size: 80px;">Games that <%= current_user.name %> is reserving</h1>
      <div class="row justify-content-center">
        <h1 style="color: white;"></h1>
      </div>
    </div>
  </div>
  <div class="cards">
    <% @reservations.each do |reservation| %>
      <% if reservation.game.photo.attached?%>
        <% background_url = cl_image_path reservation.game.photo.key %>
      <% else %>
        <% background_url = 'https://images.unsplash.com/photo-1510015632688-f18aa4c1a95e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80' %>
      <% end %>
        <div class="card">
          <div class="additional" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4)), 
            url(https://images.pexels.com/photos/326240/pexels-photo-326240.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260); 
            background-size: cover; background-position: center;">
            <div class="user-card">
              <div class="coords">
                <div class="stats">
                  <div class="text-box" style="position-absolute">
                    <p style="background-color: #09ff18bd; border-radius: 6px">From</p>
                    <div class="value"><%= reservation.start_date %></div>
                  </div>
                  <div class="text-box" style="position-absolute">
                    <p style="background-color: #ff7109cc; margin-top: 10px; border-radius: 6px">Until</p>
                    <div class="value"><%= reservation.end_date %></div>
                  </div>
                  <div class="text-box" style="position-absolute">
                    <div class="value" style="background-color: #779d94a6">Owner:</div>
                    <div class="value"><%= reservation.game.user.name %></div>
                  </div>
                  
              </div>
            </div>
            
            <div class="more-info" style="margin-top: -11rem;">
              <h1><%= link_to reservation.game.name, edit_reservation_path(reservation), style:"text-decoration: none; color: white;" %></h1>
                <%= link_to "Delete Reservation", reservation_path(reservation), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger", style:"color: white; display: block;" %>
              <div class="text-box" style="text-align: center;">      
                 
              </div>
            </div>
          </div>
        </div>
        <div class="general">
          <div class="card-category" style="background-image: url('<%= background_url %>')"></div>
          <span class="more">Mouse over the card for more info</span>
        </div>
        
        </div>
      
    <% end %>
  </div>
  </div>

app/views/reservations/show.html.erb
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h1>Reservation</h1>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <tr>
              <th>Renter</th>
              <td><%= @reservation.user.name %></td>
            </tr>
            <tr>
              <th>Start Date</th>
              <td><%= @reservation.start_date %></td>
            </tr>
            <tr>
              <th>End Date</th>
              <td><%= @reservation.end_date %></td>
            </tr>
            <tr>
              <th>Status</th>
              <td><%= @reservation.status %></td>
            </tr>
          </thead>
        </tbody>
      </table>
        <%= link_to "Edit Status", edit_reservation_path, class: "btn btn-success btn-lg m-4", style:"color: white;" %>
    </div>
  </div>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [game, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to games_path, class: "navbar-brand" do %>
    <%= image_tag "gamepad.png" %>
  <% end %>

  <% if user_signed_in? %>
    <h3> Hello, <%= current_user.name %></h3>
  <% end %>
    
  <div class="navbar">
      <% if user_signed_in? %>
        <% if current_user.photo.attached?%>
          <%= cl_image_tag current_user.photo.key, class: "avatar" %>
        <% else %>
          <%= cl_image_tag "https://images.unsplash.com/photo-1529699310859-b163e33e4556?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1122&q=80", class: "avatar" %>
        <% end %> 
          <ul class="nav nav-tabs" style="align-items: baseline; padding: 8px;">
            <li><%= link_to "Add your game", new_game_path, class: "your-game-btn" %>
            <li><%= link_to "My Games", dashboard_path, class: "dropdown-item" %></li>
            <li><%= link_to "My Reservations", reservation_dashboard_path, class: "dropdown-item" %></li>
            <li><%= link_to "Edit User Info", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul> 
      <% else %>
        <div class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
        </div>
      <% end %>
  </div>
</div>